// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vytctxgktgblnrsznhgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dGN0eGdrdGdibG5yc3puaGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjczMzcsImV4cCI6MjA3NDkwMzMzN30.rsXcqIQuTPfEvr83FxFcnSuccI9nCIzicllYFq5faB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);